In [1]:
import numpy as np

In [3]:
DNB = np.array([1,2,3,4,5])
M= np.array([6,7,8,9,0])

In [4]:
DNB.shape, M.shape

((5,), (5,))

In [15]:
CLOUD=DNB >3

In [17]:
print(CLOUD)

[False False False  True  True]


In [19]:
np.count_nonzero(CLOUD)

2

In [16]:
DNB[DNB<3]

array([1, 2])

In [11]:
M[CLOUD]

array([9, 0])

In [12]:
#we have a case that is RAW or NORM of ALL channels flattened an stacked
CASE = np.stack([DNB, M])

In [13]:
CASE.shape

(2, 5)

In [14]:
CASE[:,CLOUD]

array([[4, 5],
       [9, 0]])

In [ ]:
cloudcount 